### ISSUE TITLE
1.0.5.2更新後套用繁體化會缺字

### ISSUE THREAD

**Issue by tjhaosse** [aianlinb/LETraditionalChinese#1]
![image](https://github.com/aianlinb/LETraditionalChinese/assets/76561238/ede7c779-3516-4230-ac54-64c640989658)

會缺字

**Comment by aianlinb** [comment]
你的字型沒有套用到
請從Steam驗證檔案後重新套用
並確認程式輸出沒有出現黃色警告或紅色錯誤

**Comment by tjhaosse** [comment]
> 你的字型沒有套用到 請從Steam驗證檔案後重新套用 並確認程式輸出沒有出現黃色警告或紅色錯誤

重新驗證後，再次套用就可以了！萬分感激
